apiVersion: v1
kind: Service
metadata:
  name: mlflow
  namespace: {{ .Values.namespace }}
  labels:
    app: mlflow
spec:
  type: ClusterIP
  selector:
    app: mlflow
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
